package core

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/shniranjan/lightboot/internal/model"
)

// MenuGenerator produces iPXE script content for boot menus.
type MenuGenerator struct {
	repo      *ISORepository
	cache     *CacheManager
	log       *Logger
	bootDir   string // directory for static boot files (undionly.kpxe, ipxe.efi, etc.)
}

// NewMenuGenerator creates a new MenuGenerator.
func NewMenuGenerator(repo *ISORepository, cache *CacheManager, log *Logger, bootDir string) *MenuGenerator {
	return &MenuGenerator{
		repo:    repo,
		cache:   cache,
		log:     log,
		bootDir: bootDir,
	}
}

// BootItem is a single entry in the iPXE menu (JSON API).
type BootItem struct {
	ID        int64  `json:"id"`
	Label     string `json:"label"`
	Distro    string `json:"distro"`
	Version   string `json:"version"`
	Arch      string `json:"arch"`
	Status    string `json:"status"`
	KernelURL string `json:"kernel_url,omitempty"`
	InitrdURL string `json:"initrd_url,omitempty"`
	Ready     bool   `json:"ready"`
}

// BootMenu is the full boot menu structure.
type BootMenu struct {
	Items []BootItem `json:"items"`
}

// GetBootMenuJSON returns the boot menu as JSON for the web UI.
func (mg *MenuGenerator) GetBootMenuJSON(baseURL string) (*BootMenu, error) {
	isos, err := mg.repo.GetAllISOs()
	if err != nil {
		return nil, err
	}

	menu := &BootMenu{Items: make([]BootItem, 0, len(isos))}

	for _, iso := range isos {
		item := BootItem{
			ID:      iso.ID,
			Label:   fmt.Sprintf("%s %s (%s)", iso.Distro, iso.Version, iso.Name),
			Distro:  iso.Distro,
			Version: iso.Version,
			Arch:    iso.Arch,
			Status:  string(iso.Status),
			Ready:   iso.Status == model.StatusReady,
		}

		if iso.CachedPath != "" && iso.BootProfile != "" {
			item.KernelURL = baseURL + "/cache/" + iso.SHA256 + "/vmlinuz"
			item.InitrdURL = baseURL + "/cache/" + iso.SHA256 + "/initrd"
		}

		menu.Items = append(menu.Items, item)
	}

	return menu, nil
}

// GenerateIPXEScript builds the full iPXE script served to PXE clients.
// The server address is used for constructing absolute URLs.
func (mg *MenuGenerator) GenerateIPXEScript(serverAddr string) (string, error) {
	isos, err := mg.repo.GetReadyISOs()
	if err != nil {
		return "", err
	}

	var sb strings.Builder

	// Header
	sb.WriteString("#!ipxe\n")
	sb.WriteString("# Auto-generated by LightBoot — do not edit manually\n")
	sb.WriteString("set menu-timeout 30000\n")
	sb.WriteString("set menu-default 1\n")
	sb.WriteString(fmt.Sprintf("set server-addr %s\n", serverAddr))
	sb.WriteString("\n")

	sb.WriteString(":menu\n")
	sb.WriteString("menu LightBoot — PXE Network Boot Manager\n")
	sb.WriteString("item --gap --------------------------------\n")

	// Menu items
	for i, iso := range isos {
		profile, err := model.ParseBootProfile(iso.BootProfile)
		if err != nil || profile == nil {
			continue
		}

		label := fmt.Sprintf("%s %s (%s)", profile.Distro, profile.Version, iso.Name)

		if iso.SHA256 == "" {
			continue
		}

		kernelURL := fmt.Sprintf("http://${server-addr}/cache/%s/vmlinuz", iso.SHA256)
		initrdURL := fmt.Sprintf("http://${server-addr}/cache/%s/initrd", iso.SHA256)

		sb.WriteString(fmt.Sprintf("item boot%d %s\n", i+1, label))
		sb.WriteString(fmt.Sprintf(":boot%d\n", i+1))
		sb.WriteString(fmt.Sprintf("kernel %s %s\n", kernelURL, profile.Cmdline))
		sb.WriteString(fmt.Sprintf("initrd %s\n", initrdURL))
		sb.WriteString("boot\n")
		sb.WriteString("goto menu\n")
		sb.WriteString("\n")
	}

	// Footer with default options
	sb.WriteString("item --gap --------------------------------\n")
	sb.WriteString("item shell        iPXE command shell\n")
	sb.WriteString("item reboot       Reboot machine\n")
	sb.WriteString("item poweroff     Shutdown machine\n")
	sb.WriteString("choose --timeout ${menu-timeout} --default ${menu-default} selected && goto ${selected}\n")
	sb.WriteString("\n")
	sb.WriteString(":shell\n")
	sb.WriteString("shell\n")
	sb.WriteString("\n")
	sb.WriteString(":reboot\n")
	sb.WriteString("reboot\n")
	sb.WriteString("\n")
	sb.WriteString(":poweroff\n")
	sb.WriteString("poweroff\n")
	sb.WriteString("\n")
	sb.WriteString("# End of generated iPXE menu\n")

	return sb.String(), nil
}

// GenerateChainIPXEScript builds an iPXE script that chainloads to the full
// menu served via HTTP. This is the initial script served by TFTP/DHCP.
func (mg *MenuGenerator) GenerateChainIPXEScript(baseURL string) string {
	return fmt.Sprintf(`#!ipxe
set server-addr %s
dhcp
chain http://${server-addr}/api/boot/ipxe ||
echo Failed to load boot menu. Dropping to shell.
shell
`, baseURL)
}

// ServeIPXEHandler returns an http.Handler that serves the generated iPXE script.
func (mg *MenuGenerator) ServeIPXEHandler(serverAddr string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		script, err := mg.GenerateIPXEScript(serverAddr)
		if err != nil {
			http.Error(w, "Failed to generate iPXE menu", http.StatusInternalServerError)
			mg.log.Error("menu", "iPXE generation failed: %v", err)
			return
		}
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Write([]byte(script))
	}
}

// ServeBootMenuJSONHandler returns a JSON representation of the boot menu.
func (mg *MenuGenerator) ServeBootMenuJSONHandler(baseURL string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		menu, err := mg.GetBootMenuJSON(baseURL)
		if err != nil {
			http.Error(w, "Failed to generate menu JSON", http.StatusInternalServerError)
			mg.log.Error("menu", "JSON generation failed: %v", err)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(menu)
	}
}
